name: CI and Publish to PyPI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job 1: Run Tests
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

      - name: Install Python 3.11
        run: uv python install 3.11

      - name: Tests
        run: |
          uv run --group test pytest tests/

  # Job 2: Build and Publish to PyPI
  publish:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

      - name: Bump version
        run: |
          current_version=$(cat pyproject.toml | grep version | head -n 1 | awk -F' = ' '{print $2}' | sed 's/"//g')
          echo "Current version: $current_version"
          IFS='.' read -r major minor patch <<< "$current_version"
          new_patch=$((patch + 1))
          new_version="${major}.${minor}.${new_patch}"
          echo "New version: $new_version"
          sed -i "s/^version = .*/version = \"$new_version\"/" pyproject.toml

          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add pyproject.toml
          git commit -m "Bump version to $new_version"
          git push

      - name: Build
        run: uv build

      - name: Publish
        run: uv publish
